# Generated by Django 5.1.1 on 2025-12-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
    ]
